---
- name: clickhouse
  src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
# - name: vector_role
#   src: git@github.com:NamorNinayzuk/vector-role.git
#   scm: git
#   version: "1.0.3"
# - name: lighthouse_role
#   src: git@github.com:NamorNinayzuk/lighthouse-role.git
#   scm: git
#   version: "1.0.2"
...
